# Git Connector Configuration
# Configure git repositories to sync with shared folders

# Example 1: Public GitHub repository
[[git_connector]]
shared_folder_id = "f47ac10b-58cc-4372-a567-0e02b2c3d479"
relay_id = "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
url = "https://github.com/example/repository.git"
branch = "main"
remote_name = "origin"

# Example 2: Private repository with SSH authentication
[[git_connector]]
shared_folder_id = "12345678-1234-5678-9abc-123456789abc"
relay_id = "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
url = "git@github.com:example/private-repo.git"
branch = "develop"
remote_name = "origin"

# Example 3: GitLab repository
[[git_connector]]
shared_folder_id = "87654321-4321-8765-cba9-987654321cba"
relay_id = "another-relay-uuid-here-12345678"
url = "https://gitlab.com/example/project.git"
branch = "main"
remote_name = "gitlab"

# Configuration Notes:
# - shared_folder_id: UUID of the shared folder in the relay
# - relay_id: UUID of the relay server instance
# - url: Git repository URL (supports HTTPS and SSH)
# - branch: Target branch for pushes (default: "main")
# - remote_name: Name of the git remote (default: "origin")
#
# SSH Authentication:
# Set SSH_PRIVATE_KEY environment variable with your private key
# Use: python cli.py ssh show-pubkey to get the public key
#
# HTTPS Authentication:
# For private repos, you may need to embed credentials in the URL
# or configure git credentials separately